### ISSUE TITLE
Roadmap and development ideas

### ISSUE THREAD

**Issue by marksgraham** [marksgraham/OCT-Converter#86]
Documenting the roadmap here, feel free to pick up any issues or suggest more:

### Easy first issues
- [ ] Add type hints throughout. [This reader](https://github.com/marksgraham/OCT-Converter/blob/main/oct_converter/readers/boct.py) has an example. Types should also be removed from all the docstrings.
- [ ] Move construct definitions out of reader classes and into their own subfolder (I think @Dbrown411 is already working on this)

### Harder
- [ ] Improve .e2e reading of acquisition date/birthday acquisition. The code for [acquisition date](https://github.com/marksgraham/OCT-Converter/blob/b5acca722ba27a2cd9aa0c0b55d6ce47888e52a7/oct_converter/readers/e2e.py#L237) just uses a heuristic at the moment, and the birthdate is plain wrong, but we now have example code for how they should be properly extracted [here](https://github.com/neurodial/LibE2E/issues/5).
- [ ] Add testing. I've wanted to do this a while, but I'm a bit stumped. While we could unit test some of the codebase with synthetic data, a lot of the functionality would ideally be tested on real data (i.e. checking a change to a reader does not change the output). However, most data I have is private, so we need a way of running tests on data whilst ensuring that data cannot be accessed by anyone but me. Alternatively, we need public data from more manufactuers - currently we only have for .fda and .fds. Any ideas welcome!
- [ ] Add proper documentation. The codebase is simple but I think we have enough non-technical users that would appreciate some proper documentation hosted on read the docs or similar.

**Comment by Oli4** [comment]
What do you think about joining forces with similar projects? I thought about making OCT-Converter a dependency of eyepy to add support for more file types outside the Heidelberg universe. The E2E Reader of eyepy is going to be functional within the next few days.

**Comment by marksgraham** [comment]
What do you envision this looking like? Very happy for use to use OCT-converter as a dependency and I can look into using eyepy as I imagine it has some more fleshed out support for heidelberg than I currently have. Or are you proposing a merging into a single project?

**Comment by Oli4** [comment]
Having a "standard" package when working with OCT data in python by merging existing projects would be great and was what I once envisioned with eyepy. Increasing the number of people being involved will also increase the chance for ongoing maintenance compared to the many stale projects you find when searching the internet/github for OCT-related code. For eyepy I am the only maintainer what about OCT-Converter?

**Comment by marksgraham** [comment]
We have a few contributors, but I'm the only maintainer. Agree it would be good to have a single go-to package. Might require some more thought and discussion on exactly what this might look like. Do you want to have a call to discuss?

**Comment by drombas** [comment]
Having a standard Python package for OCT sounds fantastic.
I aimed for something similar in MATLAB [here](https://github.com/drombas/retimat). I also have quite some Python code for OCT feature extraction that I would be happy to contribute with if there was a package with a broader scope.

**Comment by Oli4** [comment]
@drombas Very impressive Matlab Package. I would be happy to integrate more feature extraction functionality in eyepy. I also thought about integrating my current work on drusen segmentation and quantification when published.
@marksgraham Yes it needs more thought and discussion and I think it's a great idea to have a call on the topic. I'll write you an Email.

**Comment by drombas** [comment]
@Oli4 happy to discuss that integration! I will look into eyepy to get an idea of how it is structured.

**Comment by Oli4** [comment]
@drombas happy to hear that. Let me know if you have any questions. I did a lot of refactoring and documentation lately that is not yet in the main branch. I aim at merging it this week. It probably makes sense to wait for this latest version.

**Comment by Oli4** [comment]
@drombas The new version of eyepy is out and it does have a documentation now :)

**Comment by naterichman** [comment]
Hi @marksgraham would you have interest in being able to save as dicom?  I am willing to put in some work to add dicom export for Fundus and OCT if that would be of interest to you

**Comment by marksgraham** [comment]
Hi @naterichman 

I'd be very interested in having dicom export! I think it's been requested in the past and i've not had the time to work on it. I'll add it to the roadmap, let me know if I can do anything to support you :)

**Comment by YaseminTurkan** [comment]
There are OCTA images in topcon and Optovue. Will there be any feature to read these images from .fda files and/or .OCT files

**Comment by big97kai** [comment]
I finised the acquisition time problem. After double checking that's right, I'll push my code... hope that's will help.
Still, I'm looking forward to finish size_y problem.

**Comment by marksgraham** [comment]
> I finised the acquisition time problem. After double checking that's right, I'll push my code... hope that's will help. Still, I'm looking forward to finish size_y problem.

That would be great, look forward to the PR!

**Comment by camlloyd** [comment]
I agree that a central repo, or at least an organisation, would be useful to help make relevant tools more _findable_.

On a related note, I have been working on a reader for in vivo confocal microscopy data, is there scope for that in this repo?

**Comment by marksgraham** [comment]
I'm happy to support placing all these tools under a single organisation, or a central repo, though I think the latter would take a fair bit of work to do!

On the microscopy reader - if you think it belongs better in this repo than anywhere else then go ahead and add it!

**Comment by Oli4** [comment]
@camlloyd  Is is confocal microscopy of the eye / retina like cSLO or AOSLO? This might be very fitting for a default ophthal package. Your OCTA reader package probably as well. 

I think the big gain would be to have modality specific datastructures that allow to process data from different devices with the same or very similar code (the idea behind the EyeVolume class in eyepy). Indexing OCT data for example should always work the same no matter how the manufacturer decided to store the data. Also converging towards a standard for storing data would be nice. Read everything but make DICOM the default for writing data for example.

**Comment by camlloyd** [comment]
@Oli4 you can learn more here: https://eyewiki.org/Confocal_Microscopy

Are you wanting `eyepy` to be _the_ central repo? Or something new?

Regardless, going forward, I would like to see:

1. Unit tests
2. Test runner in the CI
3. Synthetic datasets (e.g. for DICOM, run this against [dicom-validator](https://pydicom.github.io/dicom-validator/))
4. "Real" datasets (e.g. using imaging phantoms rather than patient data) preserved on [Zenodo](https://zenodo.org/)

**Comment by karinvangarderen** [comment]
Hi all, I'd like to pitch in to this discussion on behalf of the EyeNED team at Erasmus MC. We are eager to contribute to open-source software for ophthalmic imaging. Conversion to DICOM is one of our top priorities, and we have funding to dedicate substantial developer time to it. 

Would be great to organise a joint effort towards some comprehensive software ecosystem. Whether that's one repository or an organisation - not sure what the best course of action would be. Would it make sense to brainstorm on this?

**Comment by camlloyd** [comment]
@karinvangarderen yes, we should brainstorm together!

**Comment by Oli4** [comment]
@karinvangarderen do you already have a developer who could be included in the brainstorming?

**Comment by karinvangarderen** [comment]
I'd like to include myself and @bjliefers in this. Shall I send around a datepicker? @marksgraham would you like to join?

**Comment by marksgraham** [comment]
Sure, I'll try to join for the first meeting!

**Comment by karinvangarderen** [comment]
Scheduled a brainstorm on Thursday - looking forward to it!
@marksgraham I reached out to the gmail address in your profile, did that reach you? Let me know if there's a better way to contact you directly.
